baseURL = 'https://hugo-porto.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[author]
name = 'Kate Wolff'


[params]
description = "kate Wolff personal website"
keywords = "Kate Wolff, personal website, blog, portfolio"

# Add theme using Hugo modules
[module]
[[module.imports]]
path = "github.com/hugo-porto/theme"
