baseURL      = 'https://vanshika-jain.netlify.app/'
languageCode = 'en-us'
title        = '#VanshikaJain'


[params]
  description = "Vanshika Jain personal website"
  keywords    = "Vanshika Jain, personal website, blog, portfolio"

  [params.author]
    name = 'Vanshika Jain'


# Add theme using Hugo modules
[module]
  [[module.imports]]
    path = "github.com/hugo-porto/theme"
