baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
favicon = "images/favicon.png"

# Add theme using Hugo modules
[module]
[[module.imports]]
path = "github.com/hugo-porto/theme"
