baseURL      = 'https://hugo-porto.netlify.app/'
languageCode = 'en-us'
title        = 'My New Hugo Site'


[params]
  description = "Vanshika Jain personal website"
  keywords    = "Vanshika Jain, personal website, blog, portfolio"

  [params.author]
    name = 'John Doe'


# Add theme using Hugo modules
[module]
  [[module.imports]]
    path = "github.com/hugo-porto/theme"
